POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "Dung",
    "email": "dungksnb00@gmail.com",
    "password": "Tranvandung123"
}

###
GET http://localhost:3000/get

###
GET http://localhost:3000/set

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dungksnb00@gmail.com",
    "password": "Tranvandung123"
}

###
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzZTM4MzUzMjFiYzljMmYzY2FhOWEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjg2MzY1MDY3LCJleHAiOjE2ODYzNjU5Njd9.BaMETTjLk_-ZmazRcOCCQQx5Q9uNOihvKw00UGZUJeo

###
GET http://localhost:3000/todos
